menu/app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add_product/', views.add_product, name='add_product'),
    path('products/', views.product_list, name='products'),
    path('add_product/', views.add_product, name='add_product'),
    path('dish/<int:dish_id>/', views.dish_detail, name='dish_detail'),
    path('add_dish/', views.add_dish, name='add_dish'),
    path('add_ingredients/<int:dish_id>/<int:ingredient_count>/', views.add_ingredient, name='add_ingredients'),
]

menu/menu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ваши другие URL-адреса
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('app/', include('app.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/app/models.py
import random
import string

from django.contrib.auth.models import User
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    calories = models.IntegerField()
    proteins = models.DecimalField(max_digits=5, decimal_places=2)
    fats = models.DecimalField(max_digits=5, decimal_places=2)
    carbohydrates = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name

class Dish(models.Model):
    DISH_TYPES = [
        ('cold_appetizer', 'Холодная закуска'),
        ('hot_appetizer', 'Горячая закуска'),
        ('salad', 'Салат'),
        ('first_course', 'Первое блюдо'),
        ('main_course', 'Основное блюдо'),
        ('dessert', 'Десерт'),
        ('drink', 'Напиток'),
    ]

    name = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    description = models.TextField(blank=True)
    photo = models.ImageField(upload_to='dish_photos/', null=True, blank=True)
    dish_type = models.CharField(max_length=20, choices=DISH_TYPES)
    technology = models.TextField(blank=True)


    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.photo:
            # назвать по айдишникам не получилось(ибо их пока нет(()
            random_filename = ''.join(random.choices(string.ascii_letters + string.digits, k=20))
            extension = self.photo.name.split('.')[-1]  # Получаем расширение файла
            new_filename = f"{random_filename}.{extension}"
            self.photo.name = new_filename

        super().save(*args, **kwargs)


    def clean(self):
        if not self.name:
            raise ValidationError('Название блюда не может быть пустым.')

        if len(self.name) > 255:
            raise ValidationError('Название блюда не может превышать 255 символов.')

        if not self.description:
            raise ValidationError('Описание блюда не может быть пустым.')

        if self.photo:
            file_extension = self.photo.name.split('.')[-1].lower()
            if file_extension not in ['jpg', 'jpeg', 'png']:
                raise ValidationError('Поддерживаются только изображения в формате jpg, jpeg и png.')

        if self.dish_type not in dict(self.DISH_TYPES):
            raise ValidationError('Неверный тип блюда.')

    def clean_fields(self, exclude=None):
        self.clean()
        super().clean_fields(exclude=exclude)


class DishIngredient(models.Model):
    dish = models.ForeignKey(Dish, related_name='ingredients', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    brutto = models.DecimalField(max_digits=10, decimal_places=2)
    netto = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.product.name} - {self.brutto}g (брутто), {self.netto}g (нетто)"

    def clean(self):

        if not self.product:
            raise ValidationError(f'Продукт {self.product} не существует в базе данных.')

        if self.brutto <= 0:
            raise ValidationError(f'Брутто для {self.product.name} должно быть больше 0.')
        if self.netto <= 0:
            raise ValidationError(f'Нетто для {self.product.name} должно быть больше 0.')

    def clean_fields(self, exclude=None):
        self.clean()
        super().clean_fields(exclude=exclude)

menu/app/templates/app/add_dish.html
{% extends 'main/base.html' %}

{% block content %}
  <h1>Добавить новое блюдо</h1>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ dish_form.as_p }}

    <h3>Введите количество ингредиентов</h3>
    <input type="number" name="ingredient_count" min="1" value="1">

    <button type="submit">Далее</button>
  </form>
{% endblock %}

menu/app/templates/app/add_ingredients.html
{% extends 'main/base.html' %}


{% block content %}
  <h1>Добавление ингредиентов для блюда "{{ dish.name }}"</h1>

  <form method="post">
    {% csrf_token %}

    <h3>Количество ингредиентов: {{ ingredient_count }}</h3>

    <!-- Добавляем скрытые поля для управления формами -->
    <div style="display:none;">
      <input type="hidden" name="form-TOTAL_FORMS" value="{{ management_form.TOTAL_FORMS }}">
      <input type="hidden" name="form-INITIAL_FORMS" value="{{ management_form.INITIAL_FORMS }}">
      <input type="hidden" name="form-MAX_NUM_FORMS" value="{{ management_form.MAX_NUM_FORMS }}">
    </div>

    {% for form in formset %}
      <div class="form-row">
        <label for="{{ form.product.id_for_label }}">Ингредиент:</label>
        {{ form.product }}
        <label for="{{ form.brutto.id_for_label }}">Brutto:</label>
        {{ form.brutto }}
        <label for="{{ form.netto.id_for_label }}">Netto:</label>
        {{ form.netto }}
      </div>
    {% endfor %}

    <button type="submit">Сохранить ингредиенты</button>
  </form>
{% endblock %}

menu/app/templates/app/add_product.html
{% extends 'main/base.html' %}

{% block title %}Добавить продукт{% endblock %}

{% block content %}
    <h1>Добавить новый продукт</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить продукт</button>
    </form>

    <a href="{% url 'products' %}">Назад к списку продуктов</a>
{% endblock %}

menu/app/templates/app/add_recipe.html
{% extends 'main/base.html' %}

{% block title %}Добавить продукт{% endblock %}

{% block content %}
    <h1>Добавить новый продукт</h1>
    <p>На этой странице будет форма для добавления нового продукта в базу данных.</p>

    <form method="POST">
        {% csrf_token %}

    </form>
{% endblock %}

menu/app/templates/app/dish.html
{% extends 'main/base.html' %}

{% block content %}
  <div id="dish-container1">
    <h1>{{ dish.name }}</h1>
    <div class="author">
      <strong>Автор:</strong> {{ dish.author.username }}
    </div>
    <div class="description">
      <strong>Описание:</strong>
      <p>{{ dish.description }}</p>
    </div>
    {% if dish.photo %}
      <div class="photo">
        <img src="{{ dish.photo.url }}" alt="{{ dish.name }}">
      </div>
    {% endif %}
    <div class="technology">
      <p>Технология приготовления:</p>
      <textarea id="long-textarea" name="long-textarea" rows="4" cols="50" style="resize: both; overflow: auto;">{{ dish.technology }}</textarea>
    </div>



     <div class="dish-type">
      <strong>Тип блюда:</strong> {{ dish.get_dish_type_display }}
    </div>

    <h2>Ингредиенты</h2>
    <form method="get" action="{% url 'dish_detail' dish.id %}">
      <label for="weight">Вес блюда (г):</label>
      <input type="number" name="weight" value="{{ weight }}" step="10" min="100">
      <button type="submit">Перерасчитать</button>
    </form>

    <h3>Ингредиенты (с перерасчетом)</h3>
    <table border="1" style="width: 100%; border-collapse: collapse; font-family: Arial, sans-serif;">
      <tr style="background-color: #f2f2f2;">
        <th>Ингредиент</th>
        <th>Брутто (г)</th>
        <th>Нетто (г)</th>
        <th>Цена (руб.)</th>  <!-- Добавили цену -->
      </tr>

      {% for ingredient in ingredients %}
        <tr>
          <td>{{ ingredient.product.name }}</td>
          <td>{{ ingredient.brutto|floatformat:2 }}</td>
          <td>{{ ingredient.netto|floatformat:2 }}</td>
          <td>{{ ingredient.price|floatformat:2 }}</td>  <!-- Отображаем цену -->
        </tr>
      {% endfor %}
    </table>

    <h3>Общая цена блюда (на {{ weight }} г):</h3>
    <ul>
      <li><strong>Общая цена:</strong> {{ total_price }} руб.</li>  <!-- Отображаем общую цену -->
    </ul>

    <h3>Пищевая ценность блюда (на {{ weight }} г):</h3>
    <ul>
      <li><strong>Калории:</strong> {{ total_calories|floatformat:2 }} ккал</li>
      <li><strong>Белки:</strong> {{ total_proteins|floatformat:2 }} г</li>
      <li><strong>Жиры:</strong> {{ total_fats|floatformat:2 }} г</li>
      <li><strong>Углеводы:</strong> {{ total_carbs|floatformat:2 }} г</li>
    </ul>
  </div>
{% endblock %}

menu/app/templates/app/products.html
{% extends 'main/base.html' %}

{% block title %}Список продуктов{% endblock %}

{% block content %}
    <h1>Список продуктов</h1>
    <a href="{% url 'add_product' %}">
        <button>Добавить продукт</button>
    </a>

    <form method="GET" action="{% url 'products' %}">
        <input type="text" name="search" value="{{ search_query }}" placeholder="Поиск по названию">
        <button type="submit">Найти</button>
    </form>
    <table>
        <thead>
            <tr>
                <th>Название</th>
                <th>Цена</th>
                <th>Калорийность</th>
                <th>Белки</th>
                <th>Жиры</th>
                <th>Углеводы</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.calories }}</td>
                <td>{{ product.proteins }}</td>
                <td>{{ product.fats }}</td>
                <td>{{ product.carbohydrates }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}